export { uploadMembersProfilePicture } from './uploadImageToS3/member/member'
export { uploadInternProfilePicture } from './uploadImageToS3/member/intern'
export { uploadResearchPosterArticleImage } from './uploadImageToS3/article/research/poster'
export { uploadResearchDocumentationArticleImage } from './uploadImageToS3/article/research/documentation'
export { uploadCommunityServicePosterArticleImage } from './uploadImageToS3/article/community_service/poster'
export { uploadCommunityServiceDocumentationArticleImage } from './uploadImageToS3/article/community_service/documentation'
export { uploadInnovationPosterArticleImage } from './uploadImageToS3/article/innovation/poster'
export { uploadInnovationDocumentationArticleImage } from './uploadImageToS3/article/innovation/documentation'

export { getImage } from './getImageFromS3/index'